# ============================================
# SECRET - Datos SENSIBLES
# ============================================
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: order-service
  labels:
    app: order-service

type: Opaque

data:
  # postgres (base64)
  DB_USERNAME: cG9zdGdyZXM=
  # postgres (base64)
  DB_PASSWORD: cG9zdGdyZXM=
